=== jimmy-wims/pixlPalace/schnellbach_wims/mypalace/fichier_xml/pix-L-palace.dtd
<!ELEMENT personne(identitee*,information*)>
<!ELEMENT identitee (#PCDATA)>
<!ELEMENT information (nom*,prenom*,adressemail,date,post,mana*,vie*,xp*,niveau*)>
<!ELEMENT posts (posts*)>
<!ELEMENT post (#PCDATA)>
<!ATTLIST post type (public*|amis*|privee*) #REQUIRED >
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adressemail (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT listedespost (postpublic*,postamis*)>
<!ELEMENT postpublic (#PCDATA)>
<!ELEMENT postamis (#PCDATA)>

=== jimmy-wims/pixlPalace/schnellbach_wims/mypalace/fichier_xml/mes_amis.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE personne SYSTEM "pix-L-palace.dtd">
<?xml-stylesheet type="text/xsl" href="table.xsl"?>
<personne>
<identitee>jimmy wims</identitee>
	<information>
		<nom>tanguy</nom>
		<prenom>schnellbach</prenom>
		<adressemail>psy@hotmail.fr</adressemail>
		<date> vous êtes amis depuis le :2018-05-04 20:00:00</date>
		<posts>
			<post type="public">le 2018-03-21 19:11:54 à publié : salut jim</post>
			<post type="public">le 2018-03-21 21:13:25 à publié :  je repond à jimmy</post>
			<post type="public">le 2018-03-23 10:50:14 à publié :  bonjour</post>
			<post type="public">le 2018-03-24 10:46:21 à publié :  je repond à salut les amis</post>
			<post type="public">le 2018-03-24 10:46:43 à publié :  salut jimmy!</post>
			<post type="public">le 2018-03-24 10:47:34 à publié :  comme tout seul</post>
			<post type="public">le 2018-03-29 15:09:16 à publié :  mon premier pouce actif! (pensez à dimentionner width et height ) max</post>
			<post type="public">le 2018-03-29 15:45:22 à publié :  je ne peut pas laisser ma photo de profil comme ça!</post>
			<post type="amis" >le 2018-03-21 19:11:54 à publié : salut les amis!!</post>
		</posts>
	</information>
</personne>

=== jimmy-wims/pixlPalace/schnellbach_wims/mypalace/fichier_xml/mes_infos.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE personne SYSTEM "pix-L-palace.dtd">
<?xml-stylesheet type="text/xsl" href="liste.xsl"?>
<personne>
<identitee>wims jimmy</identitee>
	<information>
		<adressemail>wims@hotmail.fr</adressemail>
		<date> date de naissance:1998-12-08</date>
		<mana> mana :64</mana>
		<vie> vie :72</vie>
		<xp> XP :34</xp>
		<niveau> niveau :1</niveau>
		<posts>
			<post type="public">le 2018-03-21 19:11:54 √† publi√© : cool</post>
			<post type="public">le 2018-03-21 19:11:54 √† publi√© : he salut! tanguy!</post>
			<post type="public">le 2018-03-29 15:45:46 √† publi√© :  j'en ai marre de commenter tout seul
</post>
			<post type="public">le 2018-03-29 18:19:49 √† publi√© :  trop fort ! on peut aimer ses propres post mais on pert 1 mana mais √ßa nous rajoute 1 de vie! par contre si on aime pas un post d'un autre √ßa nous coute 1 de vie mais √ßa enl√®ve aussi un de vie √† l'autre mais on pert aussi 1 mana ! et enfin si on aime pas son propre post √ßa nous coute 1 de vie 1 de mana et on pert 1 de vie en plus</post>
			<post type="public">le 2018-04-20 08:27:38 √† publi√© : </post>
			<post type="public">le 2018-05-02 14:44:41 √† publi√© : </post>
			<post type="public">le 2018-05-04 11:32:21 √† publi√© : je teste les fonction</post>
			<post type="public">le 2018-05-04 13:49:18 √† publi√© : </post>
			<post type="public">le 2018-05-06 10:24:52 √† publi√© : j'ai chang√© les dossier ^^</post>
			<post type="public">le 2018-05-06 12:43:54 √† publi√© : </post>
			<post type="public">le 2018-05-07 16:10:58 √† publi√© : oui c'est genial</post>
			<post type="amis" >le 2018-03-21 19:11:54 √† publi√© : comment va tu</post>
			<post type="prive" >le 2018-03-21 19:11:54 √† publi√© : memo 2 ‡ moi meme</post>
		</posts>
	</information>
</personne>
